name: $(Build.SourceBranchName)

trigger:
  batch: false
  tags:
    include:
    - 'v*'
 
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    version=$(echo "$(Build.BuildNumber)" | cut -c2-)
    echo "##vso[task.setvariable variable=version]$version"

- template: azure-pipelines.steps.yaml
  parameters:
    version: $(version)

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
    publishFeedCredentials: NuGet
  displayName: Publish
