name: 0.0.$(System.PullRequest.PullRequestId)-pr-$(Rev:rr)

trigger: none

pool:
  vmImage: 'Ubuntu-18.04'

steps:
- template: azure-pipelines.steps.yaml
  parameters:
    version: $(Build.BuildNumber)

- task: DotNetCoreCLI@2
  inputs:
    command: push
    nuGetFeedType: internal
    packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
    publishVstsFeed: stackage
  displayName: Publish
