parameters:
  version: '0.0.0'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    feedsToUse: 'config'
    nugetConfigPath: './package/NuGet.config'
    verbosityRestore: 'Minimal'

- script: dotnet build --configuration Release --no-restore --no-incremental /p:Version=${{ parameters.version }}
  displayName: Build

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    arguments: '--configuration Release --no-build --verbosity Normal'

- script: dotnet pack --configuration Release /p:Version=${{ parameters.version }} --no-build --output $(Build.ArtifactStagingDirectory)
  displayName: Package
